[tool.poetry]
name = "recap"
version = "0.1.0"
description = ""
authors = ["Daniel <shj1103s@naver.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
